### ISSUE TITLE
Half records are missing

### ISSUE THREAD

**Issue by meule** [alexanderkuk/analyze-reformagkh#1]
Спасибо за работу!
В CSV-файле только 500k строк. Есть ли вторые 500k записей?

**Comment by kuk** [comment]
Да, но данные уже устаревшие. Сейчас лучше брать данные из https://www.reformagkh.ru/opendata?gid=2208161&page=4&pageSize=100 таблицы "Реестр домов по ..."

**Comment by meule** [comment]
Спасибо! А как лучше геокодировать адреса? Яндексом?

**Comment by kuk** [comment]
Если нужно геокодировать только большие города можно https://wiki.openstreetmap.org/wiki/Nominatim , если всю Россию, да кроме Яндекса, по-моему альтернатив нет.
